---
abstract: 'Easy creation of symbol-tables and objects'
author:
  - "Steffen \"Daode\" Nurpmeso <sdaoden@users.sf.net>"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: S-SymObj
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.8.0
